# Generated by Django 5.2 on 2025-05-04 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastFMArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('about_artist', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lastfm_url', models.URLField(blank=True, max_length=255, null=True)),
                ('listeners', models.PositiveBigIntegerField(default=0)),
                ('playcount', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LastFMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=127)),
                ('api_secret', models.CharField(max_length=127)),
                ('app_name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='LastFMImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FilePathField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ImageFetcher.lastfmartist')),
            ],
        ),
    ]
