# Generated by Django 5.2 on 2025-05-14 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_track_times_played_playlist_playhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playhistory',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.playlist'),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.track'),
        ),
    ]
