# Generated by Django 5.2 on 2025-05-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_artist_lastfm_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_type',
            field=models.CharField(choices=[('user', 'User Created'), ('auto', 'Auto Generated'), ('top', 'Top Played'), ('artist_mix', 'Artist Mix')], default='user', max_length=50),
        ),
    ]
