# Generated by Django 5.2 on 2025-05-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_playlist_playlist_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='romaji_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='romaji_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='romaji_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
